CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" character varying(20) NOT NULL,
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241107213620_InitialCreate', '9.0.0-rc.2.24474.1');

ALTER TABLE "Users" ALTER COLUMN "Password" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241116133307_remove-password-length-limit', '9.0.0-rc.2.24474.1');

CREATE TABLE "Manafacturers" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_Manafacturers" PRIMARY KEY ("Id")
);

CREATE TABLE "Models" (
    "Id" uuid NOT NULL,
    "ManafacturerId" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_Models" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Models_Manafacturers_ManafacturerId" FOREIGN KEY ("ManafacturerId") REFERENCES "Manafacturers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarListings" (
    "Id" uuid NOT NULL,
    "ModelId" uuid NOT NULL,
    "YearOfProduction" integer NOT NULL,
    "NumberOfSeats" integer NOT NULL,
    "FuelType" text NOT NULL,
    "RentalPriceType" double precision NOT NULL,
    "Location" text NOT NULL,
    "NumberOfKilometers" double precision NOT NULL,
    "RegistrationNumber" text NOT NULL,
    "Description" character varying(10000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_CarListings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarListings_Models_ModelId" FOREIGN KEY ("ModelId") REFERENCES "Models" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarListingPictures" (
    "Id" uuid NOT NULL,
    "CarListingId" uuid NOT NULL,
    "Image" text NOT NULL,
    CONSTRAINT "PK_CarListingPictures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarListingPictures_CarListings_CarListingId" FOREIGN KEY ("CarListingId") REFERENCES "CarListings" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CarListingPictures_CarListingId" ON "CarListingPictures" ("CarListingId");

CREATE INDEX "IX_CarListings_ModelId" ON "CarListings" ("ModelId");

CREATE INDEX "IX_Models_ManafacturerId" ON "Models" ("ManafacturerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241205225649_car-listing-database', '9.0.0-rc.2.24474.1');
INSERT INTO "Manafacturers" ("Id", "Name")
VALUES
    (gen_random_uuid(), 'Toyota'),
    (gen_random_uuid(), 'Volkswagen'),
    (gen_random_uuid(), 'Ford'),
    (gen_random_uuid(), 'Honda'),
    (gen_random_uuid(), 'BMW'),
    (gen_random_uuid(), 'Mercedes-Benz'),
    (gen_random_uuid(), 'Chevrolet'),
    (gen_random_uuid(), 'Nissan'),
    (gen_random_uuid(), 'Hyundai'),
    (gen_random_uuid(), 'Kia'),
    (gen_random_uuid(), 'Peugeot'),
    (gen_random_uuid(), 'Fiat'),
    (gen_random_uuid(), 'Renault'),
    (gen_random_uuid(), 'Audi'),
    (gen_random_uuid(), 'Mazda'),
    (gen_random_uuid(), 'Subaru'),
    (gen_random_uuid(), 'Volvo'),
    (gen_random_uuid(), 'Jeep'),
    (gen_random_uuid(), 'Jaguar'),
    (gen_random_uuid(), 'Land Rover'),
    (gen_random_uuid(), 'Skoda'),
    (gen_random_uuid(), 'Seat'),
    (gen_random_uuid(), 'Tesla'),
    (gen_random_uuid(), 'Suzuki'),
    (gen_random_uuid(), 'Dodge'),
    (gen_random_uuid(), 'Chrysler'),
    (gen_random_uuid(), 'Mitsubishi'),
    (gen_random_uuid(), 'Mini'),
    (gen_random_uuid(), 'Lexus'),
    (gen_random_uuid(), 'Alfa Romeo'),
    (gen_random_uuid(), 'Ferrari'),
    (gen_random_uuid(), 'Lamborghini'),
    (gen_random_uuid(), 'Porsche'),
    (gen_random_uuid(), 'Aston Martin'),
    (gen_random_uuid(), 'Bentley'),
    (gen_random_uuid(), 'Bugatti'),
    (gen_random_uuid(), 'Rolls Royce'),
    (gen_random_uuid(), 'McLaren'),
    (gen_random_uuid(), 'Pagani'),
    (gen_random_uuid(), 'Citroën'),
    (gen_random_uuid(), 'Saab'),
    (gen_random_uuid(), 'Isuzu'),
    (gen_random_uuid(), 'Hummer'),
    (gen_random_uuid(), 'Opel'),
    (gen_random_uuid(), 'Buick'),
    (gen_random_uuid(), 'GMC'),
    (gen_random_uuid(), 'Cadillac'),
    (gen_random_uuid(), 'Infinity'),
    (gen_random_uuid(), 'Acura');
  INSERT INTO "Models" ("Id", "ManafacturerId", "Name")
VALUES
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Toyota'), 'Corolla'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Toyota'), 'Camry'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Toyota'), 'RAV4'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volkswagen'), 'Golf'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volkswagen'), 'Passat'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volkswagen'), 'Tiguan'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Ford'), 'Fiesta'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Ford'), 'Focus'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Ford'), 'Explorer'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Honda'), 'Civic'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Honda'), 'Accord'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Honda'), 'CR-V'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'BMW'), '3 Series'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'BMW'), '5 Series'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'BMW'), 'X5'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mercedes-Benz'), 'C-Class'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mercedes-Benz'), 'E-Class'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mercedes-Benz'), 'GLC'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Chevrolet'), 'Malibu'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Chevrolet'), 'Impala'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Chevrolet'), 'Tahoe'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Nissan'), 'Altima'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Nissan'), 'Rogue'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Nissan'), 'Sentra'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Hyundai'), 'Elantra'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Hyundai'), 'Sonata'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Hyundai'), 'Tucson'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Kia'), 'Soul'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Kia'), 'Sportage'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Kia'), 'Sorento'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Peugeot'), '208'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Peugeot'), '3008'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Peugeot'), '5008'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Fiat'), '500'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Fiat'), 'Panda'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Fiat'), 'Tipo'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Renault'), 'Clio'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Renault'), 'Megane'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Renault'), 'Captur'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Audi'), 'A3'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Audi'), 'Q5'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Audi'), 'A6'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mazda'), 'Mazda3'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mazda'), 'CX-5'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Mazda'), 'MX-5'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Subaru'), 'Impreza'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Subaru'), 'Outback'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Subaru'), 'Forester'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volvo'), 'XC40'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volvo'), 'S60'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Volvo'), 'V90'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jeep'), 'Wrangler'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jeep'), 'Cherokee'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jeep'), 'Compass'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jaguar'), 'XE'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jaguar'), 'F-Pace'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Jaguar'), 'I-Pace'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Land Rover'), 'Range Rover'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Land Rover'), 'Discovery'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Land Rover'), 'Defender'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Skoda'), 'Octavia'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Skoda'), 'Superb'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Skoda'), 'Kodiaq'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Seat'), 'Ibiza'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Seat'), 'Leon'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Seat'), 'Ateca'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Tesla'), 'Model S'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Tesla'), 'Model 3'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Tesla'), 'Model X'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Suzuki'), 'Swift'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Suzuki'), 'Vitara'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Suzuki'), 'Jimny'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Dodge'), 'Challenger'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Dodge'), 'Charger'),
    (gen_random_uuid(), (SELECT "Id" FROM "Manafacturers" WHERE "Name" = 'Dodge'), 'Durango');
    
COMMIT;