CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" character varying(20) NOT NULL,
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241107213620_InitialCreate', '9.0.0-rc.2.24474.1');

ALTER TABLE "Users" ALTER COLUMN "Password" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241116133307_remove-password-length-limit', '9.0.0-rc.2.24474.1');

CREATE TABLE "Manafacturers" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_Manafacturers" PRIMARY KEY ("Id")
);

CREATE TABLE "Models" (
    "Id" uuid NOT NULL,
    "ManafacturerId" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_Models" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Models_Manafacturers_ManafacturerId" FOREIGN KEY ("ManafacturerId") REFERENCES "Manafacturers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarListings" (
    "Id" uuid NOT NULL,
    "ModelId" uuid NOT NULL,
    "YearOfProduction" integer NOT NULL,
    "NumberOfSeats" integer NOT NULL,
    "FuelType" text NOT NULL,
    "RentalPriceType" double precision NOT NULL,
    "Location" text NOT NULL,
    "NumberOfKilometers" double precision NOT NULL,
    "RegistrationNumber" text NOT NULL,
    "Description" character varying(10000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_CarListings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarListings_Models_ModelId" FOREIGN KEY ("ModelId") REFERENCES "Models" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarListingPictures" (
    "Id" uuid NOT NULL,
    "CarListingId" uuid NOT NULL,
    "Image" text NOT NULL,
    CONSTRAINT "PK_CarListingPictures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarListingPictures_CarListings_CarListingId" FOREIGN KEY ("CarListingId") REFERENCES "CarListings" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CarListingPictures_CarListingId" ON "CarListingPictures" ("CarListingId");

CREATE INDEX "IX_CarListings_ModelId" ON "CarListings" ("ModelId");

CREATE INDEX "IX_Models_ManafacturerId" ON "Models" ("ManafacturerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241205225649_car-listing-database', '9.0.0-rc.2.24474.1');

COMMIT;
