version: '3.8'

services:
  wheelly-db:
    image: postgres:latest
    container_name: wheelly-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@55w0rd
      POSTGRES_DB: wheely_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  api:
    image: wheelly_api:latest
    container_name: wheelly_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8080:8080"
    depends_on:
      - wheelly-db
      
volumes:
  pgdata:
